package com.iplfactssheet;

public enum SortFieldIplTeam {
     AVERAGE, STRIKING_RATES, SIX_AND_FOUR, SRTIKING_RATES_WITH_SIX_FOUR, AVERAGE_STRIKING_RATES,
     ECONOMY_RATE, STRIKING_RATES_FIVE_FOUR_WKTS, WKTS_AVEARGE, FIVE_WKTS, FOUR_WKTS, BAT_AVERAGE, BALL_AVERAGE, BAT_AVERAGE_STRIKING_RATES, BALL_AVERAGE_STRIKING_RATES, BAT_RUNS_AVERAGE, BALL_RUNS_AVERAGE, BAll_WKTS_AVEARGE, BALL_BAT_AVERAGE, BALL_BAT_RUN_WKTS, RUNS_AVERAGE
};
