package com.iplfactssheet;

public enum SortFieldIplRunns {
     AVERAGE, STRIKING_RATES, SIX_AND_FOUR, SRTIKING_RATES_WITH_SIX_FOUR, AVERAGE_STRIKING_RATES,
     ECONOMY_RATE, STRIKING_RATES_FIVE_FOUR_WKTS, RUNS_AVERAGE
};
